### ISSUE TITLE
[Bug] computed property doesn't work as expected.

### ISSUE THREAD

**Issue by 3cp** [aurelia/aurelia#534]
# 🐛 Bug Report

Computed property doesn't work as expected.

## 🤔 Expected Behavior

Expect computed property properly rendered/updated in HTML.

## 😯 Current Behavior

This simple computed property in a Todo app.

```js
get doneCount() {
  return this.todos.filter(t => t.isDone).length;
}
```

First vnext warns `Property 'filter' is being dirty-checked.` which is less than perfect. The proxy should kick in to handle this.

Second, even with dirty check, it somehow only updates `doneCount` when add/remove todo. It doesn't update the rendered doneCount when toggling a single todo isDone.

The bug can be demonstrated by https://github.com/3cp/vnext-computed-prop-bug

Just run `npm start`.

**Comment by 3cp** [comment]
Should we have some kind of resort to force a periodic update (like the old dirty check in vcurrent) to bypass this issue now?

Something like:
```js
@setInterval(300)
get doneCount() {
  return this.todos.filter(t => t.isDone).length;
}
```

**Comment by 3cp** [comment]
This code sample is fixed after #791. @bigopon what do you mean "partially address"?

**Comment by bigopon** [comment]
@3cp what you want is the efficient read on getter, where the framework would assume it can cache the read result. at the moment, it's not doing that efficiently yet. I think that's what I meant by "partially addressed".

**Comment by 3cp** [comment]
As long as it didn't break user app, we can consider this closed.

**Comment by fkleuver** [comment]
@bigopon We may have addressed this already?

**Comment by bigopon** [comment]
Yes, the latest implementation of computed should address this fully or at least of what I could see for now
